<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * example site extension layout template
 */

// this is the standard template data
$templateData = $this->templateData;
?><!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xmlns:dc="http://purl.org/dc/terms/" xmlns:foaf="http://xmlns.com/foaf/0.1/">
<head>
    <meta charset="UTF-8">
    <title><?php echo $templateData['title'] ?> &mdash; <?php echo $this->siteConfig['name'] ?></title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="generator" content="<?php echo $this->generator ?>" />
    
    <link rel="<?php echo $this->curie('http://xmlns.com/foaf/0.1/primaryTopic') ?>" href="<?php echo $this->resourceUri?>" />

    <?php if($templateData['title'] === 'Statistics') {
    		$baseJavascriptPath = $this->systemConfig->staticUrlBase. 'extensions/cubeviz/public/javascript/';
    		$baseCssPath = $this->systemConfig->staticUrlBase. 'extensions/cubeviz/public/css/'; 
    		$baseTheme = $this->systemConfig->staticUrlBase. 'extensions/themes/silverblue/' ?>
    
    	<link href="<?php echo $baseCssPath ?>IndexAction/visualization.css" media="screen" rel="stylesheet" type="text/css" />
		<link href="<?php echo $baseCssPath ?>IndexAction/legend.css" media="screen" rel="stylesheet" type="text/css" />
		<link href="<?php echo $baseCssPath ?>IndexAction/header.css" media="screen" rel="stylesheet" type="text/css" />
		<link href="<?php echo $baseCssPath ?>IndexAction/exportArea.css" media="screen" rel="stylesheet" type="text/css" />
		<link href="<?php echo $baseCssPath ?>main.css" media="screen" rel="stylesheet" type="text/css" />
		<link href="<?php echo $baseCssPath ?>foreign/Bootstrap/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
		<link href="<?php echo $baseCssPath ?>DataselectionModule/slice.css" media="screen" rel="stylesheet" type="text/css" />
		<link href="<?php echo $baseCssPath ?>DataselectionModule/measure.css" media="screen" rel="stylesheet" type="text/css" />
		<link href="<?php echo $baseCssPath ?>DataselectionModule/footer.css" media="screen" rel="stylesheet" type="text/css" />
		<link href="<?php echo $baseCssPath ?>DataselectionModule/dataSet.css" media="screen" rel="stylesheet" type="text/css" />
		<link href="<?php echo $baseCssPath ?>DataselectionModule/dataSelectionModule.css" media="screen" rel="stylesheet" type="text/css" />
		<link href="<?php echo $baseCssPath ?>DataselectionModule/component.css" media="screen" rel="stylesheet" type="text/css" />
		<link href="<?php echo $baseCssPath ?>DataselectionModule/attribute.css" media="screen" rel="stylesheet" type="text/css" />
		<link href="<?php echo $baseCssPath ?>main.css" media="screen" rel="stylesheet" type="text/css" />
		<link href="<?php echo $baseCssPath ?>foreign/FontAwesome/css/font-awesome.min.css" media="screen" rel="stylesheet" type="text/css" />
		
		<link about="" rel="update:defaultGraph" href="urn:8d12fdef-4d8a-48b3-bdd4-b9571d27fdc6"/>
		<link about="urn:8d12fdef-4d8a-48b3-bdd4-b9571d27fdc6" rel="update:updateEndpoint" href="<?php echo $this->systemConfig->staticUrlBase ?>update/"/>
		<link about="urn:8d12fdef-4d8a-48b3-bdd4-b9571d27fdc6" rel="update:queryEndpoint" href="<?php echo $this->systemConfig->staticUrlBase ?>sparql/"/>

		<!-- ontowiki stylesheets -->
	    <link rel="stylesheet" href="<?php echo $baseTheme?>styles/default.css" type="text/css" media="screen" />
	    <link rel="stylesheet" href="<?php echo $baseTheme?>styles/clickmenu.css" type="text/css" media="screen" />
	    <link rel="stylesheet" href="<?php echo $baseTheme?>styles/jquery-ui.css" type="text/css" media="screen" />
	    
	    <!-- Diachron UI stylesheets -->
	    <link type="text/css" href="<?php echo $this->baseUri ?>/css/styles.css" rel="stylesheet" />
    	<link type="text/css" href="<?php echo $this->baseUri ?>/css/bootstrap.min.css" rel="stylesheet" />

	    <!-- jQuery -->
	    <script type="text/javascript" src="<?php echo $baseTheme?>scripts/libraries/jquery.js"></script>
	    <script type="text/javascript" src="<?php echo $baseTheme?>scripts/libraries/jquery-ui.js"></script>
	    
	    <!-- included js libraries -->
    	<script type="text/javascript" src="<?php echo $baseTheme?>scripts/libraries/jquery.livequery.js"></script>
    	<script type="text/javascript" src="<?php echo $baseTheme?>scripts/libraries/jquery.clickmenu.js"></script>
    	<script type="text/javascript" src="<?php echo $baseTheme?>scripts/libraries/jquery.simplemodal.js"></script>
    	<script type="text/javascript" src="<?php echo $baseTheme?>scripts/libraries/jquery.rdfquery.rdfa-1.0.js"></script>
    	
    	<script type="text/javascript">
            var urlBase = "http://localhost/ontowiki/";
            var themeUrlBase = "http://localhost/ontowiki/extensions/themes/silverblue/";
            var _OWSESSION = "ONTOWIKI";
            var RDFAUTHOR_BASE = "http://localhost/ontowiki/libraries/RDFauthor/";
            var RDFAUTHOR_VIEW_MODE = "inline";
            var RDFAUTHOR_DEBUG = 1;
            var selectedGraph = {
                URI: "urn:8d12fdef-4d8a-48b3-bdd4-b9571d27fdc6",
                title: "Dataset Quality Graph",
                editable: true
            };
            var RDFAUTHOR_DEFAULT_GRAPH = "urn:8d12fdef-4d8a-48b3-bdd4-b9571d27fdc6";

            var selectedResource = {
                URI: "urn:8d12fdef-4d8a-48b3-bdd4-b9571d27fdc6",
                title: "Dataset Quality Graph",
                graphURI: "urn:8d12fdef-4d8a-48b3-bdd4-b9571d27fdc6"
            };
            var RDFAUTHOR_DEFAULT_SUBJECT = "urn:8d12fdef-4d8a-48b3-bdd4-b9571d27fdc6";
		</script>

    	<!-- ontowiki js -->
    	<script type="text/javascript" src="<?php echo $baseTheme?>scripts/main.js"></script>
    	<script type="text/javascript" src="<?php echo $baseTheme?>scripts/support.js"></script>
    	<script type="text/javascript" src="<?php echo $baseTheme?>scripts/jquery.ontowiki.js"></script>

    	<!-- dynamic js -->
		<script type="text/javascript" src="<?php echo $baseJavascriptPath?>libraries/CryptoJS_Md5.js"></script>
		<script type="text/javascript" src="<?php echo $baseJavascriptPath?>libraries/json2.js"></script>
		<script type="text/javascript" src="<?php echo $baseJavascriptPath?>libraries/underscore.js"></script>
		<script type="text/javascript" src="<?php echo $baseJavascriptPath?>libraries/underscore.string.js"></script>
		<script type="text/javascript">
	    	//<![CDATA[
			_.mixin(_.str.exports());    //]]>
		</script>
		<script type="text/javascript" src="<?php echo $this->systemConfig->staticUrlBase ?>extensions/cubeviz/ChartConfig.js"></script>
		<script type="text/javascript" src="<?php echo $baseJavascriptPath?>CubeVizMain.js"></script>
		<script type="text/javascript" src="<?php echo $baseJavascriptPath?>libraries/javascriptStats-1.0.1.js"></script>
		<script type="text/javascript" src="<?php echo $baseJavascriptPath?>libraries/highcharts.js"></script>
		<script type="text/javascript" src="<?php echo $baseJavascriptPath?>libraries/highcharts-more.js"></script>
		<!-- head scripts -->
    	<?php echo $this->headScript() ?>
		
    <?php } else { ?>

    	<link type="text/css" href="<?php echo $this->baseUri ?>/css/jquery-ui-themes/smoothness/jquery-ui.min.css" rel="stylesheet" />
    	<link type="text/css" href="<?php echo $this->baseUri ?>/css/styles.css" rel="stylesheet" />
    	<link type="text/css" href="<?php echo $this->baseUri ?>/css/bootstrap.min.css" rel="stylesheet" />

    	<script type="text/javascript" src="<?php echo $this->baseUri ?>/js/jquery-1.11.1.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUri ?>/js/jquery-ui-1.11.0.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUri ?>/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUri ?>/js/lod-access.js"></script>

    <?php } ?>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    
    <style>
    	body.javascript-on div.window-buttons .button-windowminimize {
    		display: none;
    	}    
    	
    	div.ui-widget-overlay {
    		display:none;
    	}
    </style>

</head>

<body<?php foreach ($this->namespaces as $prefix => $ns): ?><?php echo ' xmlns:' . $prefix . '="' . $ns . '"' ?><?php endforeach; ?>>

	<div class="container">
	    <?php echo $this->renderx(); ?>
	    <!-- Example row of columns for a Feed -->
	    <div class="row">
	        <?php echo $this->partial('diachron/types/feed.phtml', $this->templateData) ?>
	    </div>
	    <hr>
	    <footer>
	        <p><!-- TODO: define &copy; tag  --></p>
	    </footer>
	</div> <!-- /container -->

</body>

</html>

