<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * example site extension layout template
 */

// this is the standard template data
$templateData           = $this->templateData;
?><!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xmlns:dc="http://purl.org/dc/terms/" xmlns:foaf="http://xmlns.com/foaf/0.1/">
<head>
    <meta charset="UTF-8">
    <title><?php echo $templateData['title'] ?> &mdash; <?php echo $this->siteConfig['name'] ?></title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="generator" content="<?php echo $this->generator ?>" />

    <link rel="<?php echo $this->curie('http://xmlns.com/foaf/0.1/primaryTopic') ?>" href="<?php echo $this->resourceUri?>" />
    <link type="text/css" href="<?php echo $this->baseUri ?>/css/styles.css" rel="stylesheet" />
    <link type="text/css" href="<?php echo $this->baseUri ?>/css/jquery-ui-themes/smoothness/jquery-ui.min.css" rel="stylesheet" />
    <link type="text/css" href="<?php echo $this->baseUri ?>/css/bootstrap.min.css" rel="stylesheet" />
    
    <script type="text/javascript" src="<?php echo $this->baseUri ?>/js/jquery-1.11.1.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUri ?>/js/jquery-ui-1.11.0.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUri ?>/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUri ?>/js/lod-access.js"></script>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

<?php
    // includes the GA header script
    // includes the exhibit header links
    // other head scripts
    $this->headScript();
?>
</head>

<body<?php
    foreach ($this->namespaces as $prefix => $ns): ?><?php echo ' xmlns:' . $prefix . '="' . $ns . '"' ?><?php endforeach; ?>>

<div class="container">
    <?php echo $this->renderx(); ?>
    <!-- Example row of columns for a Feed -->
    <div class="row">
        <?php echo $this->partial('diachron/types/feed.phtml', $this->templateData) ?>
    </div>
    <hr>
    <footer>
        <p><!-- TODO: define &copy; tag  --></p>
    </footer>
</div> <!-- /container -->

</body>
</html>

