<ul id="tab-container" class="nav nav-tabs" role="tablist">
	<li><a href="Detail">Detail</a></li>
	<li><a href="Statistics">Statistics</a></li>
	<li class="active"><a>Assessment</a></li>
</ul>
<div class="tab-content">
	<div class="tab-pane active" id="detail">
		<div class="hero-unit">
		<h1><?php echo $this->title ?></h1>
		<?php
		    // uses default content properties
		    echo $this->literal(array('tag' => 'div', 'class' => 'content'));
		?>
		</div>
	</div>
</div>