<ul id="tab-container" class="nav nav-tabs" role="tablist">
	<li class="active"><a href="#detail">Detail</a></li>
	<li><a href="#stats">Statistics</a></li>
	<li><a href="#assessment">Assessment</a></li>
</ul>
<div class="tab-content">
	<div class="tab-pane active" id="detail">
		<div class="layout-col" style="width:300px;">
			<h4>Facets</h4>
			<div class="panel panel-default controls-bar">
				<div class="panel panel-default">
				  <div class="panel-heading">Category</div>
				  <div class="panel-body">
				  	<div id="btnListCategories" class="btn-group-vertical btn-group-sm btn-list" data-toggle="buttons">
					</div>
				  </div>
				</div>
				<div class="panel panel-default">
				  <div class="panel-heading">Dimension</div>
				  <div class="panel-body">
				  	<div id="btnListDimensions" class="btn-group-vertical btn-group-sm btn-list" data-toggle="buttons">
					</div>
				  </div>
				</div>
				<div class="panel panel-default">
				  <div class="panel-heading">Metric</div>
				  <div class="panel-body">
				  	<div id="btnListMetrics" class="btn-group-vertical btn-group-sm btn-list" data-toggle="buttons">
					</div>
				  </div>
				</div>
			</div>
			<h4>Filters</h4>
			<div class="panel panel-default controls-bar">
				<div class="checkbox">
					<label>
						<input type="checkbox" value="">Available
					</label>
				</div>
			</div>
		</div>
		<div class="layout-col" style="min-width:500px; max-width:700px">
			<div class="input-group">
				<span class="input-group-addon">
			  		<span class="glyphicon glyphicon-search"></span>
			  	</span>
			  	<input type="text" class="form-control" placeholder="Search">
			</div>
			<div style="width:100%; margin-top:15px;">
				<div id="lst-datasets" class="list-group">
					<a href="#" class="list-group-item">
				    	<h4 class="list-group-item-heading">A collection of LREC2014 submissions</h4>
				    	<p class="list-group-item-text">
				    		The submission is the pointer to papers and to authors.
				    	</p>
				    	<p class="list-group-item-text lst-datasets-actions">
			    			<button type="button" class="btn btn-primary btn-xs">Application/rdf+xml</button>&nbsp;&nbsp;
							<button type="button" class="btn btn-success btn-xs">Quality metadata/rdf+xml</button>
				    	</p>
				  	</a>
				  	<a href="#" class="list-group-item">
				    	<h4 class="list-group-item-heading">RDF Licenses</h4>
				    	<p class="list-group-item-text">
				    		This small dataset contains licenses (suitable for general works, data, etc.) expressed as RDF.
				    	</p>
				    	<p class="list-group-item-text lst-datasets-actions">
			    			<button type="button" class="btn btn-primary btn-xs">Application/turtle</button>&nbsp;&nbsp;
							<button type="button" class="btn btn-success btn-xs">Quality metadata/turtle</button>
				    	</p>
				  	</a>
				  	<a href="#" class="list-group-item">
				    	<h4 class="list-group-item-heading">DisGeNET</h4>
				    	<p class="list-group-item-text">
				    		Linked Data version of DisGeNET, which is a Resource Description Framework (RDF) representation of a vast 
				    		database integrating gene-disease associations from several...
				    	</p>
				    	<p class="list-group-item-text lst-datasets-actions">
			    			<button type="button" class="btn btn-primary btn-xs">Application/turtle</button>&nbsp;&nbsp;
							<button type="button" class="btn btn-success btn-xs">Quality metadata/turtle</button>&nbsp;&nbsp;
							<button type="button" class="btn btn-info btn-xs">api/sparql</button>&nbsp;&nbsp;
							<button type="button" class="btn btn-warning btn-xs">rdf/void</button>&nbsp;&nbsp;
							<button type="button" class="btn btn-default btn-xs">metadata/schema</button>
				    	</p>
				  	</a>
				</div>
			</div>
		</div>
		<div class="layout-clear"></div>
	</div>
	<div class="tab-pane" id="stats">
		Lots of stats
	</div>
	<div class="tab-pane" id="assessment">
		Lots of assessment
	</div>
</div>

<script type="text/javascript">

	// An object containing the hierarchy of categories -> dimensions -> metrics
	var metricsSet = null;

	// Document ready event handler
	$(function() {
		// Load quality categories, dimensions and metrics
		loadAvailableMetrics();
		buildCategoriesList();
		buildDimensionsList();
	});

	$('#tab-container a').click(function (e) {
	  e.preventDefault();
	  $(this).tab('show');
	});
	
	$('#lst-datasets .list-group-item').click(function (e) {
	  e.preventDefault();
	});

	function loadAvailableMetrics() {
		// Retrieve existing metrics from the Quality knowledgebase
		var arrMetrics = lodDataAccess.selectMetrics();
		
		// Build a convenient mapped representation of the hierarchy of categories -> dimensions -> metrics
		metricsSet = {};
		var curMetric = null;
		var curCategory = null;
		var curDimension = null;
		
		for(var m = 0; m < arrMetrics.length; m++) {
			curMetric = arrMetrics[m];
			
			// Check if the current category has already been added to the set
			curCategory = metricsSet[curMetric.category_name];
			if(curCategory === undefined || curCategory === null) {
				curCategory = {};
				metricsSet[curMetric.category_name] = curCategory;
			}

			// Check if the current dimension has already been added to the category
			curDimension = curCategory[curMetric.dimension_name];
			if(curDimension === undefined || curDimension === null) {
				curDimension = new Array();
				curCategory[curMetric.dimension_name] = curDimension;
			}

			// Add the current metric to the dimension, which is an array of metrics
			curDimension.push({ name: curMetric.metric_name, uri: curMetric.metric_uri });
		}
	}
	
	// Load quality categories defined in the DQM knowledgebase and fill the category-selection list
	function buildCategoriesList() {
		var btnListCategories = $("#btnListCategories");

		// Remove previous categories
		btnListCategories.empty();
		
		// A map specifying the selected categories is attached to the DOM element containing categories
		var mapSelCategories = {};
		btnListCategories.data("mapSelCategories", mapSelCategories);
		
		// Add elements to buttons list of categories
		$.map(metricsSet, function(categoryObj, curCatName) {
			// Create a DOM button corresponding to each category
			btnListCategories.append("<button type='button' class='btn btn-default' " + 
					"onclick='toggleCategory(\"" + curCatName + "\")'>" + curCatName + "</button>");

			// Add the category to the map of selected categories, as unselected
			mapSelCategories[curCatName] = false;
		});
	}

	// Add/remove the toggled category to/from the set of selected categories
	function toggleCategory(selected) {		
		// A map specifying the selected categories should be attached to the DOM element containing categories 
		// (loadCategories should've been already executed)
		var mapSelCategories = $("#btnListCategories").data("mapSelCategories");

		// Mark the category as selected/not-selected depending on its previous state
		mapSelCategories[selected] = !(mapSelCategories[selected]);

		// Update buttons list corresponding to the dimensions of the selected categories
		buildDimensionsList();
	}

	// Load quality dimensions defined in the DQM knowledgebase and fill the dimension-selection list
	function buildDimensionsList() {
		var btnListDimensions = $("#btnListDimensions");
		var mapSelCategories = $("#btnListCategories").data("mapSelCategories");

		// Remove previous dimensions
		btnListDimensions.empty();
		
		// A map specifying the selected dimensions is attached to the DOM element containing dimensions
		var mapSelDimensions = {};
		btnListDimensions.data("mapSelDimensions", mapSelDimensions);

		// Extract the dimensions of each selected category
		$.map(mapSelCategories, function(isCatSelected, curCatName) {
			// Show the dimensions of the selected categories only
			if(isCatSelected) {
				// Add elements to buttons list of dimensions
				$.map(metricsSet[curCatName], function(dimensionObj, curDimName) {
					// Create a DOM button corresponding to each dimension
					btnListDimensions.append("<button type='button' class='btn btn-default' " + 
							"onclick='toggleDimension(\"" + curDimName + "\")'>" + curDimName + "</button>");

					// Add the category to the map of selected categories, as unselected
					mapSelDimensions[curDimName] = false;
				});
			}
		});
	}

</script>